### ISSUE TITLE
Selfmute does not work in groupwatch channel

### ISSUE THREAD

**Issue by oosinoots** [tailoric/Pouty-Bot-Discord#41]
![User being able to type in groupwatch channel](https://user-images.githubusercontent.com/63559579/80934633-c4aeb580-8de6-11ea-8913-1f791d5aea0b.png)

![User's profile showing he's self-muted](https://user-images.githubusercontent.com/63559579/80934678-e14aed80-8de6-11ea-8dcb-7d9a400723df.png)

**Comment by tailoric** [comment]
This has nothing to do with the bot :bruhchiko:
